In [88]:
import pandas as pd
import numpy as np

In [89]:
df_combined = pd.concat(
    pd.read_excel(r"C:\Users\RossBennfors\Documents\My Tableau Prep Repository\Datasources\Prep Challenge Data sets\PD 2021 Wk 3 Input.xlsx", sheet_name=None)
)

In [90]:
df_combined = df_combined.reset_index(level=0).rename(columns={'level_0': 'Sheet Name'}).reset_index(drop=True)

In [91]:
df_melted = df_combined.melt(id_vars=['Date', 'Sheet Name'], var_name='Type_Product', value_name='Value')

In [92]:
df_melted[['Type', 'Product']] = df_melted['Type_Product'].str.split(' - ', expand=True)

In [93]:
df_melted.drop(columns=['Type_Product'], inplace=True)

In [94]:
df_melted['quarter'] = df_melted['Date'].dt.to_period('Q')

In [95]:
df_melted['quarter'] = df_melted['quarter'].dt.quarter

In [97]:
df_melted

          Date  Sheet Name  Value      Type  Product  quarter
0   2021-01-21  Manchester     13       New  Saddles        1
1   2021-02-21  Manchester      1       New  Saddles        1
2   2021-03-21  Manchester      8       New  Saddles        1
3   2021-04-21  Manchester      3       New  Saddles        2
4   2021-05-21  Manchester      2       New  Saddles        2
..         ...         ...    ...       ...      ...      ...
475 2021-08-21  Birmingham     11  Existing     Bags        3
476 2021-09-21  Birmingham     24  Existing     Bags        3
477 2021-10-21  Birmingham     16  Existing     Bags        4
478 2021-11-21  Birmingham     12  Existing     Bags        4
479 2021-12-21  Birmingham     10  Existing     Bags        4

[480 rows x 6 columns]

In [98]:
df_OP1 = df_melted.groupby(['Product', 'quarter'])['Value'].sum().reset_index()

In [ ]:
# Output 1:
df_OP1

      Product  quarter  Value
0        Bags        1    683
1        Bags        2    593
2        Bags        3    564
3        Bags        4    541
4   Mudguards        1   1006
5   Mudguards        2    442
6   Mudguards        3    331
7   Mudguards        4    674
8     Saddles        1    321
9     Saddles        2    280
10    Saddles        3    361
11    Saddles        4    337
12     Wheels        1    319
13     Wheels        2    303
14     Wheels        3    306
15     Wheels        4    290

In [101]:
df_OP2 = df_melted.groupby(['Product', 'Sheet Name', 'Type'])['Value'].sum().reset_index()

In [105]:
df_OP2['Store'] = df_OP2['Sheet Name']
df_OP2.drop(columns=['Sheet Name'], inplace=True)

In [106]:
#Output 2:
df_OP2

      Product      Type  Value       Store
0        Bags  Existing    218  Birmingham
1        Bags       New    312  Birmingham
2        Bags  Existing    246       Leeds
3        Bags       New    233       Leeds
4        Bags  Existing    229      London
5        Bags       New    251      London
6        Bags  Existing    171  Manchester
7        Bags       New    286  Manchester
8        Bags  Existing    130        York
9        Bags       New    305        York
10  Mudguards  Existing    266  Birmingham
11  Mudguards       New    256  Birmingham
12  Mudguards  Existing    180       Leeds
13  Mudguards       New    270       Leeds
14  Mudguards  Existing    182      London
15  Mudguards       New    291      London
16  Mudguards  Existing    258  Manchester
17  Mudguards       New    180  Manchester
18  Mudguards  Existing    269        York
19  Mudguards       New    301        York
20    Saddles  Existing    185  Birmingham
21    Saddles       New    123  Birmingham
22    Saddles  Existing    146       Leeds
23    Saddles       New    106       Leeds
24    Saddles  Existing    163      London
25    Saddles       New    123      London
26    Saddles  Existing    152  Manchester
27    Saddles       New     97  Manchester
28    Saddles  Existing    110        York
29    Saddles       New     94        York
30     Wheels  Existing     78  Birmingham
31     Wheels       New    137  Birmingham
32     Wheels  Existing    108       Leeds
33     Wheels       New    158       Leeds
34     Wheels  Existing    129      London
35     Wheels       New    115      London
36     Wheels  Existing    138  Manchester
37     Wheels       New    123  Manchester
38     Wheels  Existing    137        York
39     Wheels       New     95        York