In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('C:\\Users\\RossBennfors\\Documents\\My Tableau Prep Repository\\Datasources\\Prep Challenge Data sets\\PD 2021 Wk 1 Input.xlsx', sheet_name='Bike Sales')

In [18]:
df[['Store', 'Bike']] = df['Store - Bike'].str.split(' - ', expand=True)

In [19]:
df = df.drop(columns=['Store - Bike'])

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            1000 non-null   int64
 1   Customer Age        1000 non-null   int64
 2   Bike Value          1000 non-null   int64
 3   Existing Customer?  1000 non-null   str
 4   Date                1000 non-null   datetime64[us]
 5   Store               1000 non-null   str
 6   Bike                1000 non-null   str
dtypes: datetime64[us](1), int64(3), str(3)
memory usage: 54.8 KB

In [22]:

count_before = df['Bike'].str.startswith(('m', 'M'), na=False).sum()
count_before

np.int64(400)

In [23]:
df['Bike'] = np.where(df['Bike'].str.startswith(('r', 'R')), 'Road', np.where(df['Bike'].str.startswith(('g', 'G')), 'Gravel', 'Mountain'))

In [26]:
count_after = df['Bike'].str.startswith(('m', 'M'), na=False).sum()
count_after

np.int64(400)

In [29]:
df['Quarter'] = pd.to_datetime(df['Date']).dt.quarter

In [31]:
df['Day of Month'] = pd.to_datetime(df['Date']).dt.day

In [42]:
df_final = df.iloc[10:]

In [43]:
df_final.drop(columns=['Date'])

,Order ID,Customer Age,Bike Value,Existing Customer?,Store,Bike,Quarter,Day of Month
10,11,57,902,No,Birmingham,Road,4,4
11,12,31,946,Yes,Leeds,Road,1,17
12,13,17,1296,Yes,Birmingham,Road,4,25
13,14,59,1166,Yes,Manchester,Road,3,18
14,15,24,1781,No,Manchester,Mountain,4,10
...,...,...,...,...,...,...,...,...
995,996,42,3460,No,London,Mountain,3,3
996,997,48,3409,No,London,Mountain,1,17
997,998,81,2534,No,London,Mountain,1,26
998,999,37,4312,Yes,London,Gravel,2,25
999,1000,35,1200,Yes,Leeds,Gravel,1,18

In [44]:
df_final = df_final.iloc[:, [6,4,5,0,1,2,3]]

In [45]:
df_final

,Bike,Date,Store,Order ID,Customer Age,Bike Value,Existing Customer?
10,Road,2021-10-04,Birmingham,11,57,902,No
11,Road,2021-01-17,Leeds,12,31,946,Yes
12,Road,2021-10-25,Birmingham,13,17,1296,Yes
13,Road,2021-07-18,Manchester,14,59,1166,Yes
14,Mountain,2021-10-10,Manchester,15,24,1781,No
...,...,...,...,...,...,...,...
995,Mountain,2021-09-03,London,996,42,3460,No
996,Mountain,2021-01-17,London,997,48,3409,No
997,Mountain,2021-03-26,London,998,81,2534,No
998,Gravel,2021-05-25,London,999,37,4312,Yes
999,Gravel,2021-02-18,Leeds,1000,35,1200,Yes