In [7]:
import pandas as pd
import numpy as np
import string

In [5]:
df = pd.read_csv('C:\\Users\\RossBennfors\\Documents\\My Tableau Prep Repository\\Datasources\\Prep Challenge Data sets\\PD 2021 Wk 2 Input.csv')

In [10]:
df['Model'] = df['Model'].str.replace('\d+', '', regex=True)

<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\RossBennfors\AppData\Local\Temp\ipykernel_55016\786119375.py:1: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  df['Model'] = df['Model'].str.replace('\d+', '', regex=True)

In [14]:
df['Model'] = df['Model'].str.replace('/', '', regex=True)

In [18]:
df['Order Value'] = df['Quantity'] * df['Value per Bike']

In [25]:
df_agg1 = df.groupby(['Model', 'Bike Type']).agg(
    Quantity_Sold=('Quantity', 'sum'),
    Avg_Value_per_Bike=('Value per Bike', 'mean'),
    Order_Value=('Order Value', 'sum')
)

In [26]:
df_agg1['Avg_Value_per_Bike'] = df_agg1['Avg_Value_per_Bike'].round(1)

In [28]:
df_agg1

                 Quantity_Sold  Avg_Value_per_Bike  Order_Value
Model Bike Type
BROM  Gravel               186              2335.5       433885
      Mountain             277              2359.3       674770
      Road                 257              2500.7       656539
GIA   Gravel               323              2303.2       733087
      Mountain             425              2378.9      1021329
      Road                 407              2184.7       896695
KONA  Gravel               324              2463.7       791841
      Mountain             330              2487.0       820537
      Road                 273              2430.2       647684
ORRO  Gravel               151              2640.0       411644
      Mountain              87              2382.4       206550
      Road                  84              2237.7       181300
SPEC  Gravel               974              2355.6      2295397
      Mountain             960              2422.7      2344504
      Road                 937              2356.3      2195597

In [32]:
df

,Bike Type,Store,Order Date,Quantity,Value per Bike,Shipping Date,Model,Order Value
0,Mountain,Manchester,15/05/2020,4,1543,01/06/2020,GIA,6172
1,Gravel,Manchester,16/06/2020,2,2076,24/06/2020,GIA,4152
2,Road,Birmingham,04/05/2020,1,2616,13/05/2020,GIA,2616
3,Gravel,York,05/09/2020,2,1359,19/09/2020,GIA,2718
4,Gravel,Birmingham,28/03/2020,4,1599,04/04/2020,GIA,6396
...,...,...,...,...,...,...,...,...
1995,Road,Manchester,02/06/2020,2,3504,20/06/2020,SPEC,7008
1996,Mountain,York,07/09/2020,2,1109,21/09/2020,SPEC,2218
1997,Road,London,10/12/2020,3,1032,11/12/2020,SPEC,3096
1998,Gravel,London,10/02/2020,2,2303,11/02/2020,SPEC,4606
1999,Mountain,Manchester,10/07/2020,2,2903,30/07/2020,SPEC,5806

In [34]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Shipping Date'] = pd.to_datetime(df['Shipping Date'], format='%d/%m/%Y')

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Bike Type       2000 non-null   str
 1   Store           2000 non-null   str
 2   Order Date      2000 non-null   datetime64[us]
 3   Quantity        2000 non-null   int64
 4   Value per Bike  2000 non-null   int64
 5   Shipping Date   2000 non-null   datetime64[us]
 6   Model           2000 non-null   str
 7   Order Value     2000 non-null   int64
dtypes: datetime64[us](2), int64(3), str(3)
memory usage: 125.1 KB

In [37]:
df['Days to Ship'] = (df['Shipping Date'] - df['Order Date']).dt.days

In [41]:
df_agg2 = df.groupby(['Store', 'Model']).agg(
    Quantity_Sold=('Quantity', 'sum'),
    Avg_Days_to_Ship=('Days to Ship', 'mean'),
    Order_Value=('Order Value', 'sum')
)

In [43]:
df_agg2['Avg_Days_to_Ship'] = df_agg2['Avg_Days_to_Ship'].round(1)

In [47]:
#Output 1:
df_agg1

                 Quantity_Sold  Avg_Value_per_Bike  Order_Value
Model Bike Type
BROM  Gravel               186              2335.5       433885
      Mountain             277              2359.3       674770
      Road                 257              2500.7       656539
GIA   Gravel               323              2303.2       733087
      Mountain             425              2378.9      1021329
      Road                 407              2184.7       896695
KONA  Gravel               324              2463.7       791841
      Mountain             330              2487.0       820537
      Road                 273              2430.2       647684
ORRO  Gravel               151              2640.0       411644
      Mountain              87              2382.4       206550
      Road                  84              2237.7       181300
SPEC  Gravel               974              2355.6      2295397
      Mountain             960              2422.7      2344504
      Road                 937              2356.3      2195597

In [46]:
# Output 2:
df_agg2

                  Quantity_Sold  Avg_Days_to_Ship  Order_Value
Store      Model
Birmingham BROM             155              11.8       349759
           GIA              269               9.9       581733
           KONA             184              10.6       435694
           ORRO              86              11.4       216169
           SPEC             651              10.6      1488013
Leeds      BROM             150               9.8       389116
           GIA              203              11.2       460151
           KONA             208               9.2       498341
           ORRO              55              11.9       126334
           SPEC             570              10.4      1431894
London     BROM             133              11.0       324635
           GIA              228              10.7       548821
           KONA             216              10.7       524879
           ORRO              61               9.4       151734
           SPEC             578              11.2      1358343
Manchester BROM             137              10.9       339832
           GIA              204              11.0       466613
           KONA             148              10.5       370481
           ORRO              43               8.4       118800
           SPEC             614              11.1      1451471
York       BROM             145               9.8       361852
           GIA              251              10.4       593793
           KONA             171              11.1       430667
           ORRO              77               9.0       186457
           SPEC             458              10.4      1105777